name: Build Plugin

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install, build
        run: |
          yarn
          yarn build
          sed 's/dist\/index\.js/index.js/g' package.json > dist/package.json
        env:
          CI: true
